version: "3.7"

services:
  recipes:
    networks:
      - backend
    image: recipes
    restart: unless-stopped
    ports:
      - "2016:8000"
  caddy:
    networks:
      - backend
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:

networks:
  backend:
